create table if not exists Movie (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	title varchar UNIQUE NOT NULL,
	release_year int NOT NULL,
	director_id int NOT NULL
);

create table if not exists Director (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar UNIQUE NOT NULL
);